In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression ,LogisticRegression


In [7]:

df = pd.read_csv("cgpa_package_data.csv")

In [8]:
df.head(3)

CGPA  Package (LPA)
0   9.8           25.0
1   9.6           24.0
2   9.5           23.5

In [9]:
x = df.iloc[:,:-1]
y = df["Package (LPA)"]

In [11]:
new_df = df.head(10)

In [12]:
from sklearn.model_selection import LeaveOneOut ,LeavePOut , StratifiedKFold , KFold , cross_val_score , cross_val_predict

In [21]:
x_new = new_df.iloc[:,:-1]
y_new = new_df["Package (LPA)"]

In [23]:
lo = LeavePOut(p=2)

for train , test in lo.split(x_new,y_new):
    print(train , test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [24]:
lo = KFold(n_splits=5)

for train , test in lo.split(x_new,y_new):
    print(train , test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [26]:
# lo = StratifiedKFold(n_splits=5)
# for train , test in lo.split(x_new,y_new):
#     print(train , test)


# this  will give an error because stratifiedKFold only works in classification analysisi not in regression analysis

In [27]:
from sklearn.model_selection import cross_val_score , cross_val_predict


In [37]:
p = cross_val_score(LinearRegression(),x,y , cv=KFold(n_splits=10))

In [38]:
p.sort()

In [39]:
p*100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])