In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection  import train_test_split
import seaborn as sns
from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.metrics import confusion_matrix , f1_score , ConfusionMatrixDisplay
 

In [2]:

df = pd.read_csv("Social_Network_Ads.csv")
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [6]:
df["Purchased"].value_counts() # value counts shows that is the data is imbalanced or not 

# in this case it is showing the dataset is imbalanced 
# because the purchase count it is showing that it is imbalanced


Purchased
0    257
1    143
Name: count, dtype: int64

In [25]:
df.__delitem__  # there was gender which was in string which was creating conflicts between sting and integers thats why i deleted it from the dataset 
df.head(3)

User ID  Age  EstimatedSalary  Purchased
0  15624510   19            19000          0
1  15810944   35            20000          0
2  15668575   26            43000          0

In [26]:
new_df = df

In [28]:
new_df.head(3)

User ID  Age  EstimatedSalary  Purchased
0  15624510   19            19000          0
1  15810944   35            20000          0
2  15668575   26            43000          0

In [34]:
x = new_df.iloc[:,:-2]
y = new_df["Purchased"]

In [74]:
x_test , x_train , y_test ,y_train = train_test_split(x,y,test_size=0.2 , random_state=42)


In [75]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)*100

64.0625

In [76]:
lr.predict([[46	 , 28000]])

# yaha par dataset unbalanced hai isliye wo zero hi de raha hai
# matlab zero dominating hai apan ne upar hi nikal liya that ki dtaset unbalanced hai karke
# refer cell number 6 

c:\Users\HP\healthcare\noman\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [77]:
x = new_df.iloc[:,:-2]
y = new_df["Purchased"]

In [78]:
from imblearn.under_sampling import RandomUnderSampler

# new module in python learned on day -- 14-6-2024

In [79]:
ru = RandomUnderSampler()
ru.fit(x,y)

RandomUnderSampler()

In [80]:
ru_x , ru_y = ru.fit_resample(x,y)

# aise agar ham define karate hai variables to ham seperate data dekh sakte hai 
# x aur y axis main
# aur ek bat undersampling large dataset ko small dataset me convt karata hai

In [81]:
ru_y.value_counts()

# now see the data is balanced 
# both x and y means probability of occuring the values that is 0 for false and 1 for true is equal 

Purchased
0    143
1    143
Name: count, dtype: int64

In [82]:
x_train , x_test , y_train , y_test = train_test_split(ru_x , ru_y , test_size=0.2 , random_state=42)

In [83]:
lr = LogisticRegression()
lr.fit(x_train , y_train)

LogisticRegression()

In [84]:
lr.score(x_test , y_test)*100

41.37931034482759

In [85]:
lr.predict([[19 ,19000]])

c:\Users\HP\healthcare\noman\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [88]:
lr.predict([[46	 , 20000]])

c:\Users\HP\healthcare\noman\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [89]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [91]:
ro = RandomOverSampler()
ro_x , ro_y = ro.fit_resample(x,y)

In [95]:
ro_y.value_counts()


Purchased
0    257
1    257
Name: count, dtype: int64

In [96]:
x_train1 , x_test1, y_train1, y_test1 = train_test_split(ro_x , ro_y , test_size=0.2 , random_state=42)

In [98]:
lr1 = LogisticRegression()
lr1.fit(x_train1 , y_train1)
lr1.score(x_test1 , y_test1)*100

45.63106796116505

In [100]:
lr1.predict([[19 , 19000]])

c:\Users\HP\healthcare\noman\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)