In [2]:
import numpy as np



In [3]:
list = [1,2 , 3,4 ,5]

In [31]:
list

[1, 2, 3, 4, 5]

In [32]:
np.array

<function numpy.array>

In [33]:
np.array(list)  #1d vector

array([1, 2, 3, 4, 5])

In [34]:
len(np.array(list))

5

In [35]:
list3= [[1,2 , 4] , [2, 3, 4] ,  [4, 5, 6,]]

In [36]:
list3

[[1, 2, 4], [2, 3, 4], [4, 5, 6]]

In [37]:
numparr = np.array(list3)

In [38]:
numparr

array([[1, 2, 4],
       [2, 3, 4],
       [4, 5, 6]])

In [39]:
np.array(list3).shape

(3, 3)

In [44]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [45]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [47]:
np.random.randint(5 , size = 2,2)

SyntaxError: positional argument follows keyword argument (3467314224.py, line 1)